// WARNING: DO NOT EDIT THIS FILE, IT IS AUTOGENERATED
/** @type {import("c3ide2-types").Effect} */
const Config = {
    addonType: "effect",
    id: "mikal_screen_space_shadows",
    name: "Screen Space Shadows",
    version: "1.0.0",
    category:
        // "blend",
        // "distortion",
        // "normal-mapping",
        // "tiling",
        // "other",
        "color",
    author: "Mikal",
    website: "https://www.construct.net",
    documentation: "https://www.construct.net",
    description: "Description",
    supportedRenderers: ["webgl2"],
    blendsBackground: false,
    usesDepth: true,
    crossSampling: false,
    preservesOpaqueness: true,
    animated: false,
    mustPredraw: false,
    extendBox: {
        horizontal: 0,
        vertical: 0,
    },
    isDeprecated: false,
    parameters: [
        /*
    {
      type:
        "float"
        "percent"
        "color"
      ,
      id: "property_id",
      value: 0,
      uniform: "uPropertyId",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Property Name",
      desc: "Property Description",
    }
    */
        {
            type: "float",
            id: "lightX",
            value: 0,
            uniform: "uLightX",
            // precision: "lowp" // defaults to lowp if omitted
            interpolatable: true,
            name: "Light X (screen space)",
            desc: "Light X (screen space)",
        },
        {
            type: "float",
            id: "lightY",
            value: 0,
            uniform: "uLightY",
            interpolatable: true,
            name: "Light Y (screen space)",
            desc: "Light Y (screen space)",
        },
        {
            type: "float",
            id: "lightZ",
            value: 0,
            uniform: "uLightZ",
            interpolatable: true,
            name: "Light Z (screen space)",
            desc: "Light Z (screen space)",
        },
        {
            type: "float",
            id: "depthScale",
            value: 1.0,
            uniform: "uDepthScale",
            interpolatable: true,
            name: "Depth Scale",
            desc: "Depth Scale",
        },
        {
            type: "float",
            id: "shadowIntensity",
            value: 5.0,
            uniform: "uShadowIntensity",
            interpolatable: true,
            name: "Shadow Intensity",
            desc: "Controls the intensity of the shadows",
        },
        {
            type: "float",
            id: "softShadow",
            value: 0.25,
            uniform: "uSoftShadow",
            interpolatable: true,
            name: "Soft Shadow",
            desc: "Controls the softness of the shadow edges",
        },
        {
            type: "float",
            id: "samples",
            value: 16,
            uniform: "uSamples",
            interpolatable: false,
            name: "Samples",
            desc: "Number of samples used in shadow calculation",
        },
        {
            type: "float",
            id: "stepScale",
            value: 1.0,
            uniform: "uStepScale",
            interpolatable: false,
            name: "Step Scale",
            desc: "Step Scale",
        },
    ],
};

module.exports = Config;
